[package]
name = "xross-example"
version = "3.0.0"
edition = "2024"


[lib]
crate-type = ["cdylib"]


[dependencies]
rand = "0.10.0"
xross-core = { path = "../../xross-core", version = "3.0.0", features = ["tokio"] }
tokio = { version = "1.0", features = ["full"] }
