[package]
name = "xross-macros"
version = "0.1.0"
edition = "2024"

[lib]
# これにより proc-macro としてコンパイルされます
proc-macro = true

[dependencies]
serde.workspace = true
serde_json.workspace = true

# ワークスペース内の別パッケージを依存に加える
xross-metadata = { path = "../xross-metadata" }

# 手続き型マクロ開発にほぼ必須のライブラリ（後述）
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
regex = "1.12.2"
heck = "0.5.0"
