[package]
name = "xross-core"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
